//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServicio.ServicioJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Paquete/", ConfigurationName="ServicioJava.Servidor")]
    public interface Servidor {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Paquete/Servidor/operationRequest", ReplyAction="http://Paquete/Servidor/operationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(operation))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumirServicio.ServicioJava.operationResponse operation(ConsumirServicio.ServicioJava.operationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Paquete/Servidor/operationRequest", ReplyAction="http://Paquete/Servidor/operationResponse")]
        System.Threading.Tasks.Task<ConsumirServicio.ServicioJava.operationResponse> operationAsync(ConsumirServicio.ServicioJava.operationRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Paquete/Servidor/helloRequest", ReplyAction="http://Paquete/Servidor/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(helloResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hello))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(operation))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsumirServicio.ServicioJava.helloResponse1 hello(ConsumirServicio.ServicioJava.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Paquete/Servidor/helloRequest", ReplyAction="http://Paquete/Servidor/helloResponse")]
        System.Threading.Tasks.Task<ConsumirServicio.ServicioJava.helloResponse1> helloAsync(ConsumirServicio.ServicioJava.helloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Paquete/")]
    public partial class helloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Paquete/")]
    public partial class hello : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Paquete/")]
    public partial class operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operation", WrapperNamespace="http://Paquete/", IsWrapped=true)]
    public partial class operationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Paquete/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public operationRequest() {
        }
        
        public operationRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operationResponse", WrapperNamespace="http://Paquete/", IsWrapped=true)]
    public partial class operationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Paquete/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public operationResponse() {
        }
        
        public operationResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://Paquete/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Paquete/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://Paquete/", IsWrapped=true)]
    public partial class helloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Paquete/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse1() {
        }
        
        public helloResponse1(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServidorChannel : ConsumirServicio.ServicioJava.Servidor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServidorClient : System.ServiceModel.ClientBase<ConsumirServicio.ServicioJava.Servidor>, ConsumirServicio.ServicioJava.Servidor {
        
        public ServidorClient() {
        }
        
        public ServidorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServidorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServidorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirServicio.ServicioJava.operationResponse ConsumirServicio.ServicioJava.Servidor.operation(ConsumirServicio.ServicioJava.operationRequest request) {
            return base.Channel.operation(request);
        }
        
        public object[] operation(int arg0) {
            ConsumirServicio.ServicioJava.operationRequest inValue = new ConsumirServicio.ServicioJava.operationRequest();
            inValue.arg0 = arg0;
            ConsumirServicio.ServicioJava.operationResponse retVal = ((ConsumirServicio.ServicioJava.Servidor)(this)).operation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirServicio.ServicioJava.operationResponse> ConsumirServicio.ServicioJava.Servidor.operationAsync(ConsumirServicio.ServicioJava.operationRequest request) {
            return base.Channel.operationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicio.ServicioJava.operationResponse> operationAsync(int arg0) {
            ConsumirServicio.ServicioJava.operationRequest inValue = new ConsumirServicio.ServicioJava.operationRequest();
            inValue.arg0 = arg0;
            return ((ConsumirServicio.ServicioJava.Servidor)(this)).operationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirServicio.ServicioJava.helloResponse1 ConsumirServicio.ServicioJava.Servidor.hello(ConsumirServicio.ServicioJava.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ConsumirServicio.ServicioJava.helloRequest inValue = new ConsumirServicio.ServicioJava.helloRequest();
            inValue.name = name;
            ConsumirServicio.ServicioJava.helloResponse1 retVal = ((ConsumirServicio.ServicioJava.Servidor)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirServicio.ServicioJava.helloResponse1> ConsumirServicio.ServicioJava.Servidor.helloAsync(ConsumirServicio.ServicioJava.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicio.ServicioJava.helloResponse1> helloAsync(string name) {
            ConsumirServicio.ServicioJava.helloRequest inValue = new ConsumirServicio.ServicioJava.helloRequest();
            inValue.name = name;
            return ((ConsumirServicio.ServicioJava.Servidor)(this)).helloAsync(inValue);
        }
    }
}
